


INSERT INTO destination (destination) VALUES
                                          ('Paris'), ('New York'), ('Tokyo'), ('London'), ('Sydney'), ('Los Angeles'),
                                          ('Madrid'), ('Rome'), ('Barcelona'), ('Hong Kong'), ('Singapore'), ('Bangkok'),
                                          ('Toronto'), ('Vancouver'), ('Melbourne'), ('Auckland'), ('Dubai'), ('Istanbul'),
                                          ('Mumbai'), ('Rio de Janeiro'), ('Cape Town'), ('Seoul'), ('Shanghai'), ('Beijing'),
                                          ('Buenos Aires'), ('San Francisco'), ('Miami'), ('Las Vegas'), ('Chicago'), ('Houston');

INSERT INTO guide (first_name, last_name) VALUES
                                              ('John', 'Doe'), ('Jane', 'Smith'), ('Sarah', 'Lee'), ('David', 'Johnson'), ('Emily', 'Garcia'),
                                              ('William', 'Taylor'), ('Jessica', 'Brown'), ('Michael', 'Miller'), ('Lisa', 'Jones'), ('Robert', 'Davis'),
                                              ('Karen', 'Rodriguez'), ('Christopher', 'Martinez'), ('Ashley', 'Gonzalez'), ('Daniel', 'Wilson'), ('Maria', 'Anderson');

INSERT INTO trip (price, departure_date, return_date, destination_id, guide_id) VALUES
                                                                                    (1000.00, '2023-03-01', '2023-03-07', 1, 1),
                                                                                    (1500.00, '2023-04-01', '2023-04-07', 2, 2),
                                                                                    (3000.00, '2023-08-01', '2023-05-07', 3, 1),
                                                                                    (2000.00, '2023-05-01', '2023-05-07', 1, 1),
                                                                                    (2500.00, '2023-06-01', '2023-06-07', 2, 3),
                                                                                    (1800.00, '2023-07-01', '2023-07-07', 3, 4),
                                                                                    (2800.00, '2023-08-01', '2023-08-07', 4, 5),
                                                                                    (2200.00, '2023-09-01', '2023-09-07', 5, 6),
                                                                                    (1700.00, '2023-10-01', '2023-10-07', 6, 7),
                                                                                    (1900.00, '2023-11-01', '2023-11-07', 7, 8),
                                                                                    (2300.00, '2023-12-01', '2023-12-07', 8, 9),
                                                                                    (2600.00, '2024-01-01', '2024-01-07', 9, 10),
                                                                                    (2900.00, '2024-02-01', '2024-02-07', 10, 11),
                                                                                    (3100.00, '2024-03-01', '2024-03-07', 11, 12),
                                                                                    (3400.00, '2024-04-01', '2024-04-07', 12, 13),
                                                                                    (2700.00, '2024-05-01', '2024-05-07', 13, 14),
                                                                                    (2400.00, '2024-06-01', '2024-06-07', 14, 15),
                                                                                    (3200.00, '2024-07-01', '2024-07-07', 15, 1),
                                                                                    (3000.00, '2024-08-01', '2024-08-07', 16, 2),
                                                                                    (2100.00, '2024-09-01', '2024-09-07', 17, 3),
                                                                                    (2600.00, '2024-10-01', '2024-10-07', 18, 4),
                                                                                    (2900.00, '2024-11-01', '2024-11-07', 19, 5),
                                                                                    (2200.00, '2024-12-01', '2024-12-07', 20, 6);

INSERT INTO app_user (first_name, last_name, passport_number, email, password, app_user_role, locked, enabled) VALUES
                                                                                                                   ('John', 'Doe', '123456', 'john.doe@example.com', 'password123', 'USER', false, true),
                                                                                                                   ('Jane', 'Doe', '654321', 'jane.doe@example.com', 'password456', 'ADMIN', false, true),
                                                                                                                   ('Bob', 'Smith', '987654', 'bob.smith@example.com', 'password789', 'USER', true, true),
                                                                                                                   ('Alice', 'Johnson', '234567', 'alice.johnson@example.com', 'passwordabc', 'USER', false, true),
                                                                                                                   ('David', 'Brown', '765432', 'david.brown@example.com', 'passworddef', 'USER', false, true),
                                                                                                                   ('Karen', 'Garcia', '890123', 'karen.garcia@example.com', 'passwordghi', 'USER', false, true),
                                                                                                                   ('Robert', 'Wilson', '456789', 'robert.wilson@example.com', 'passwordjkl', 'USER', false, true),
                                                                                                                   ('Lisa', 'Taylor', '012345', 'lisa.taylor@example.com', 'passwordmno', 'USER', false, true),
                                                                                                                   ('Steven', 'Anderson', '567890', 'steven.anderson@example.com', 'passwordpqr', 'USER', false, true),
                                                                                                                   ('Sarah', 'Martinez', '901234', 'sarah.martinez@example.com', 'passwordstu', 'USER', false, true);

INSERT INTO app_user_trips (trip_id, app_user_id) VALUES
                                                      (1, 1),
                                                      (1, 2),
                                                      (2, 2),
                                                      (3, 1),
                                                      (3, 2),
                                                      (4, 3),
                                                      (5, 4),
                                                      (5, 5),
                                                      (6, 6),
                                                      (6, 7),
                                                      (7, 8),
                                                      (7, 9),
                                                      (8, 10),
                                                      (9, 1),
                                                      (9, 2),
                                                      (10, 3),
                                                      (10, 4),
                                                      (11, 5),
                                                      (11, 6),
                                                      (12, 7),
                                                      (12, 8),
                                                      (13, 9),
                                                      (13, 10),
                                                      (14, 1),
                                                      (14, 3),
                                                      (15, 5),
                                                      (15, 7),
                                                      (16, 9),
                                                      (16, 10),
                                                      (17, 2),
                                                      (17, 4),
                                                      (18, 6),
                                                      (18, 8),
                                                      (19, 1),
                                                      (19, 10),
                                                      (20, 2),
                                                      (20, 9);
